// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using bytelibAPI.Data;

#nullable disable

namespace bytelibAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("bytelibAPI.Models.Livro", b =>
                {
                    b.Property<int>("LivroId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Autor")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Capa_URL")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PDF_Url")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("TotalPaginas")
                        .HasColumnType("int");

                    b.HasKey("LivroId");

                    b.ToTable("Livros");
                });

            modelBuilder.Entity("bytelibAPI.Models.User", b =>
                {
                    b.Property<string>("NomeUsuario")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("SenhaHash")
                        .HasColumnType("longtext");

                    b.HasKey("NomeUsuario");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("bytelibAPI.Models.UserLivro", b =>
                {
                    b.Property<string>("NomeUsuario")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("LivroId")
                        .HasColumnType("int");

                    b.Property<double>("Progresso")
                        .HasColumnType("double");

                    b.HasKey("NomeUsuario", "LivroId");

                    b.HasIndex("LivroId");

                    b.ToTable("UsuariosLivros");
                });

            modelBuilder.Entity("bytelibAPI.Models.UserLivro", b =>
                {
                    b.HasOne("bytelibAPI.Models.Livro", "Livro")
                        .WithMany("UsersLivros")
                        .HasForeignKey("LivroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("bytelibAPI.Models.User", "User")
                        .WithMany("UsersLivros")
                        .HasForeignKey("NomeUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Livro");

                    b.Navigation("User");
                });

            modelBuilder.Entity("bytelibAPI.Models.Livro", b =>
                {
                    b.Navigation("UsersLivros");
                });

            modelBuilder.Entity("bytelibAPI.Models.User", b =>
                {
                    b.Navigation("UsersLivros");
                });
#pragma warning restore 612, 618
        }
    }
}
